"""Canonical typed provider ports for Gate G node authors."""

from .contracts import (
    ASRProvider,
    ASRRequest,
    EmbeddingItem,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingResponse,
    EmbeddingVector,
    LLMMessage,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    ProducedBlob,
    ProviderCallContext,
    ProviderDescriptor,
    ProviderError,
    ProviderErrorCategory,
    ProviderErrorCode,
    ProviderKind,
    ProviderRegistry,
    ProviderResultMeta,
    ProviderTranscript,
    ProviderTranscriptSegment,
    ProviderTranscriptWord,
    TTSProvider,
    TTSRequest,
    TTSResponse,
    VLMDescription,
    VLMInput,
    VLMProvider,
    VLMRequest,
    VLMResponse,
    VoiceDescriptor,
)

__all__ = [
    "ASRProvider", "ASRRequest", "EmbeddingItem", "EmbeddingProvider", "EmbeddingRequest", "EmbeddingResponse", "EmbeddingVector",
    "LLMMessage", "LLMProvider", "LLMRequest", "LLMResponse", "ProducedBlob", "ProviderCallContext", "ProviderDescriptor",
    "ProviderError", "ProviderErrorCategory", "ProviderErrorCode", "ProviderKind", "ProviderRegistry", "ProviderResultMeta",
    "ProviderTranscript", "ProviderTranscriptSegment", "ProviderTranscriptWord", "TTSProvider", "TTSRequest", "TTSResponse",
    "VLMDescription", "VLMInput", "VLMProvider", "VLMRequest", "VLMResponse", "VoiceDescriptor",
]
